spring:
  #thymeleaf配置
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  #datasource配置
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowable_demo?useUnicode=true&characterEncoding=utf-8&nullCatalogMeansCurrent=true&serverTimezone=GMT%2B8
    username: root
    password: admin123456

flowable:  database-schema-update: false  process:    async-history:      executor:        auto-activate: false